spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

security:
  jwt:
    secret: ZGZzZGZmRGZzZGZnZHNoZ3NmaHN0aHp2RkRGU0RWRFNGc2Rmc2Rm
    access: 3600000
    refresh: 2592000000
